In [1]:
import numpy as np


In [2]:
test_array=np.array(["1","4",5,8],float)


In [3]:
test_array

array([1., 4., 5., 8.])

In [4]:
type(test_array[0])

numpy.float64

In [5]:
np.array([[1,4,5,6],[11,22,3,4,],[1,2,4,5]],np.float32)


array([[ 1.,  4.,  5.,  6.],
       [11., 22.,  3.,  4.],
       [ 1.,  2.,  4.,  5.]], dtype=float32)

In [7]:
test_array.shape

(4,)

In [29]:
matrix  = [[[1,2,5,8],[1,2,5,8],[1,2,5,8]],
          [[1,2,5,8],[1,2,5,8],[1,2,5,8]]]
matrix
t=np.array(matrix,int)
print(t)
t.shape
t.ndim

[[[1 2 5 8]
  [1 2 5 8]
  [1 2 5 8]]

 [[1 2 5 8]
  [1 2 5 8]
  [1 2 5 8]]]


3

In [41]:
tensor  = [[[1,2,5,8],[1,2,5,8],[1,2,5,8],[1,2,5,8],[1,2,5,8],[1,2,5,8]], 
           [[2,2,5,8],[1,2,5,8],[1,2,5,8],[1,2,5,8],[1,2,5,8],[1,2,5,8]], 
           [[3,2,5,8],[1,2,5,8],[1,2,5,8],[1,2,5,8],[1,2,5,8],[1,2,5,8]], 
           [[4,2,5,8],[1,2,5,8],[1,2,5,8],[1,2,5,8],[1,2,5,8],[1,2,5,8]],
          [[4,2,5,8],[1,2,5,8],[1,2,5,8],[1,2,5,8],[1,2,5,8],[1,2,5,8]]]
print(np.array(tensor, int).shape)
#()
tensor=np.array(tensor, int)
print(tensor)

(5, 6, 4)
[[[1 2 5 8]
  [1 2 5 8]
  [1 2 5 8]
  [1 2 5 8]
  [1 2 5 8]
  [1 2 5 8]]

 [[2 2 5 8]
  [1 2 5 8]
  [1 2 5 8]
  [1 2 5 8]
  [1 2 5 8]
  [1 2 5 8]]

 [[3 2 5 8]
  [1 2 5 8]
  [1 2 5 8]
  [1 2 5 8]
  [1 2 5 8]
  [1 2 5 8]]

 [[4 2 5 8]
  [1 2 5 8]
  [1 2 5 8]
  [1 2 5 8]
  [1 2 5 8]
  [1 2 5 8]]

 [[4 2 5 8]
  [1 2 5 8]
  [1 2 5 8]
  [1 2 5 8]
  [1 2 5 8]
  [1 2 5 8]]]


In [42]:
tensor.ndim

3

In [62]:
tensor2=np.array([[[1,2,3],[1,2,3],[1,2,3],[1,2,3]],
                  [[1,2,3],[1,2,3],[1,2,3],[1,2,3]]],int)
tensor_ndim=tensor2.ndim
tensor_shape=tensor2.shape
print(tensor2)
print(tensor_ndim)
print(tensor_shape)#(2,3)
#모양과 차원은 다른 의미
#(z,y,x)

[[[1 2 3]
  [1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]
  [1 2 3]]]
3
(2, 4, 3)
